### PR TITLE
Fixed your stuff and added pyc to the gitignore

### PR DESCRIPTION
**Pull request by KenwoodFox**
Added pyc to the gitignore

### CODE REVIEW

**Review by OneBiteAidan — CHANGES_REQUESTED** [review]
D:\TextBasedAdeventure-joes-branch\TextBasedAdeventure-joes-branch>py WynncraftButTextBased.py
Files in 'D:\\TextBasedAdeventure-joes-branch\\TextBasedAdeventure-joes-branch': ['.gitattributes', '.gitignore', 'AdventureMaps.py', 'bank.py', 'character_info.py', 'classes.py', 'items.py', 'questboard.py', 'shopfunctions.py', 'shopinfo.py', 'shopinfos', 'TextBasedAdventureFunctions.py', 'townsquare.py', 'WynncraftButTextBased.py', '__init__.py']
Traceback (most recent call last):
  File "WynncraftButTextBased.py", line 11, in <module>
    ragni_armor_shop = yaml.load(file, Loader=yaml.FullLoader)
  File "C:\Users\5730d\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\5730d\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "C:\Users\5730d\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\5730d\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\5730d\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\5730d\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\5730d\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\5730d\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\5730d\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\5730d\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\5730d\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\5730d\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\5730d\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\5730d\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Users\5730d\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "C:\Users\5730d\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\5730d\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "shopinfos/ragniarmorshop.yaml", line 10, column 11
could not find expected ':'
  in "shopinfos/ragniarmorshop.yaml", line 12, column 9


Code still broken my guy

**Review by KenwoodFox — COMMENTED** [review]
You literally undid all my changes with this commit, did you forget to switch branches or something? this is awful!

**Comment by KenwoodFox** [comment]
Im going to override your comit

**Review by OneBiteAidan — APPROVED** [review]
Gay

**Pull request merged**
